### ISSUE TITLE
Is cli port option redundant?

### ISSUE THREAD

**Issue by dellgreen** [ChrisMacNaughton/cargo-cacher#17]
As a new user it was confusing that you can set the port in the external URL and a separate port option.
Would it be less confusing to remove the port option in favour of extracting the port from the external URL via rust's URL crate?

https://docs.rs/url/2.1.1/url/

**Comment by jcaesar** [comment]
My two cents, because I added the url option:

I kept the two separate because when running in docker, you may want your external port to be in the 1-1023 range but run cargo-cacher as non-root inside docker where it can't listen on those ports. Other than that, there may also be the possibility of having an (nginx or traeffik or whatnot) reverse proxy running in front of cargo cacher.

I guess both are fairly odd use-cases for cargo-cacher and I wouldn't be too sad to see those die in favour of simplicity.

**Comment by dellgreen** [comment]
That's a great use case, thanks for clearing that up. It should stay as is then.
